Repository jenkinsci/ansible-plugin, pull requests merged in 2023-07, with the labels that each got.

#99 Parallelize Tests
  pom.xml
Labels: chore, tests

#106 Bump minimal Jenkins core to 2.401.3
  pom.xml
Labels: chore, dependencies

#108 Revert "JENKINS-49812 Escape shell special characters"
  src/main/java/org/jenkinsci/plugins/ansible/AbstractAnsibleInvocation.java
Labels: bug
