Repository jenkinsci/ansible-plugin, pull requests merged in 2023-11, with the labels that each got.

#150 Ensure correct bom version when jenkins version updated
  updatecli/updatecli.d/update-jenkins-version.yml
Labels: chore

#151 Ensure correct bom version when jenkins version updated (fix typo from previous PR)
  updatecli/updatecli.d/update-jenkins-version.yml
Labels: chore, skip-changelog

#148 Workspace folder doesn't exist in newly created ansible pipelines
  src/main/java/org/jenkinsci/plugins/ansible/CLIRunner.java
Labels: bug
