Repository jenkinsci/ansible-plugin, pull requests merged in 2023-06, with the labels that each got.

#84 Add minimal pipeline test for ssh pass
  src/test/java/org/jenkinsci/plugins/ansible/PipelineTest.java
  src/test/resources/pipelines/ansiblePlaybookSshPass.groovy
Labels: tests

#85 JENKINS-49812 Escape shell special characters
  src/main/java/org/jenkinsci/plugins/ansible/AbstractAnsibleInvocation.java
Labels: bug

#88 Handle Number-typed extra var values.
  README.md
  src/main/java/org/jenkinsci/plugins/ansible/AbstractAnsibleInvocation.java
  src/main/java/org/jenkinsci/plugins/ansible/workflow/AnsiblePlaybookStep.java
  src/test/java/org/jenkinsci/plugins/ansible/PipelineTest.java
  src/test/resources/pipelines/extraVarsNumeric.groovy
Labels: enhancement

#89 JENKINS-49056 Pipeline Support for Ansible Adhoc Commands
  README.md
  src/main/java/org/jenkinsci/plugins/ansible/workflow/AnsibleAdhocStep.java
  src/main/resources/org/jenkinsci/plugins/ansible/workflow/AnsibleAdHocStep/config.jelly
  src/main/resources/org/jenkinsci/plugins/ansible/workflow/AnsibleAdHocStep/help.html
  src/test/java/org/jenkinsci/plugins/ansible/PipelineTest.java
  src/test/resources/pipelines/adhocCommand.groovy
Labels: enhancement
