Repository jenkinsci/ansible-plugin, pull requests merged in 2024-01, with the labels that each got.

#171 Add coverage badge
  README.md
Labels: documentation

#176 Suppress warnings for spotbugs 4.8.3
  src/main/java/org/jenkinsci/plugins/ansible/AnsibleAdHocCommandBuilder.java
  src/main/java/org/jenkinsci/plugins/ansible/AnsiblePlaybookBuilder.java
  src/main/java/org/jenkinsci/plugins/ansible/AnsibleVaultBuilder.java
  src/main/java/org/jenkinsci/plugins/ansible/ExtraVar.java
  src/main/java/org/jenkinsci/plugins/ansible/jobdsl/context/AnsibleContext.java
Labels: skip-changelog

#183 Bump testcontainers to 1.19.4
  pom.xml
Labels: dependencies, tests
