Repository jenkinsci/ansible-plugin, pull requests merged in 2024-06, with the labels that each got.

#219 Bump jenkins core
  pom.xml
Labels: chore, dependencies

#220 Update tested ansible versions
  README.md
  src/test/java/org/jenkinsci/plugins/ansible/PipelineTest.java
Labels: tests

#225 Add support for Boolean extra-var interpretation
  src/main/java/org/jenkinsci/plugins/ansible/AbstractAnsibleInvocation.java
Labels: enhancement

#227 Update java-version to 17 for Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore
