Repository jenkinsci/ansible-plugin, pull requests merged in 2025-08, with the labels that each got.

#340 Test Java 25
  Jenkinsfile
  pom.xml
Labels: chore, dependencies

#341 Update tested ansible version
  README.md
  src/test/java/org/jenkinsci/plugins/ansible/PipelineTest.java
Labels: tests

#342 Ban JUnit 4 imports
  pom.xml
Labels: chore
