Repository jenkinsci/ansible-plugin, pull requests merged in 2025-03, with the labels that each got.

#301 Migrate tests to JUnit5
  src/test/java/org/jenkinsci/plugins/ansible/AnsibleAdHocCommandInvocationTest.java
  src/test/java/org/jenkinsci/plugins/ansible/AnsibleVaultInvocationTest.java
  src/test/java/org/jenkinsci/plugins/ansible/CompatibilityTest.java
  src/test/java/org/jenkinsci/plugins/ansible/PipelineTest.java
  src/test/java/org/jenkinsci/plugins/ansible/jobdsl/DslJobRule.java
  src/test/java/org/jenkinsci/plugins/ansible/jobdsl/JobDslIntegrationTest.java
Labels: tests

#305 Require Jenkins 2.479.3
  pom.xml
Labels: dependencies

#306 Remove useless spotbugs supression
  pom.xml
  src/main/java/org/jenkinsci/plugins/ansible/AnsibleAdHocCommandBuilder.java
  src/main/java/org/jenkinsci/plugins/ansible/ExtraVar.java
Labels: chore
